server:
  port: 20001

keycloak:
  # turn off keycloak spring boot auto-configuration:
  # We only want to use Spring Security without servlet container specific infrastructure
  # This allows us to pull the Keycloak configuration from here instead of keycloak.json
  enabled: false

  realm: acme
# Note the /u path is custom configuration, by default it's just /auth
  auth-server-url: http://sso.tdlabs.local:8899/u/auth
# The client_id
  resource: app-frontend-springboot
  credentials:
# The client_secret
     secret: 4822a740-20b9-4ff7-bbed-e664f4a70eb6
  ssl-required: external
# Configures what principal.getName() will return
  principal-attribute: preferred_username
  use-resource-role-mappings: true
  token-minimum-time-to-live: 30


todo-backend:
  server: http://apps.tdlabs.local:20000